# Generated by Django 5.1.2 on 2026-07-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_technology_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(default='fa-code', help_text='Example: fa-users, fa-motorcycle, fa-robot', max_length=50),
        ),
    ]
