# Generated by Django 5.1.2 on 2026-08-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Example: devicon-python-plain, devicon-django-plain, devicon-postgresql-plain', max_length=100),
        ),
    ]
