# Generated by Django 5.1.2 on 2026-08-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_technology_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, help_text='Example: fa-python, fa-docker, fa-git-alt', max_length=50),
        ),
    ]
