# Generated by Django 5.1.2 on 2026-08-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_technology_icon_class_technology_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='technology_icons/'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
